version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: ./project-management
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Mapping Nginx port 80 to host 5173 for familiar access
    depends_on:
      - backend
    restart: unless-stopped
